server {
 listen 80;
 root /usr/share/nginx/html;
 index index.html;
 location / { try_files $uri $uri/ /index.html; }
 add_header X-Content-Type-Options nosniff;
 add_header Referrer-Policy same-origin;
}
