import {useDeferredValue,useMemo,useState} from 'react';
import Pagination,{usePagination} from './Pagination';
import {money} from './math.mjs';
import {whatsapp} from './outputActions';
import {customerHistory} from './customerHistory.mjs';
type Row=Record<string,any>;
export default function Customers({data,manager,setModal,customerDue,safe}:{data:Row;manager:boolean;setModal:(v:Row)=>void;customerDue:(r:Row)=>number;safe:(fn:()=>Promise<any>)=>Promise<any>}){
 const [kind,setKind]=useState('customer'),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[detail,setDetail]=useState<string>('');
 const deferredSearch=useDeferredValue(search).toLowerCase();
 const contacts=useMemo(()=>data.customers.filter((c:Row)=>(c.customer_kind||'customer')===kind).map((c:Row)=>customerHistory(data,c)).filter((c:Row)=>c.balance>0),[data,kind]);
 const shown=useMemo(()=>contacts.filter((c:Row)=>(filter==='all'||(filter==='unpaid'&&c.balance>0)||(filter==='recent'&&c.last&&Date.now()-new Date(c.last.sale_date).getTime()<30*86400000))&&[c.full_name,c.mobile,c.cnic,...c.phones.map((p:Row)=>p.name)].some(v=>String(v||'').toLowerCase().includes(deferredSearch))),[contacts,filter,deferredSearch]);
 const {visible,pagination}=usePagination<Row>(shown,kind+filter+deferredSearch);
 const selected=contacts.find((c:Row)=>c.id===detail);
 const selectedInvoices=usePagination<Row>(selected?.realSales||[],'invoices:'+detail),selectedPayments=usePagination<Row>(selected?.paymentHistory||[],'payments:'+detail);
 if(selected)return <section className="panel customer-page"><div className="customer-page-head"><div><h2>{selected.full_name}</h2><small>{kind==='shopkeeper'?'Shopkeeper':'Customer'} details</small></div><button onClick={()=>setDetail('')}>Back to customers</button></div><div className="customer-detail-card">{[['Phone',selected.mobile],['CNIC',selected.cnic],['Address',selected.address],['Total invoices',selected.realSales.length],['Total purchased',money(selected.totalSpent)],['Outstanding',money(selected.balance)],['Notes',selected.notes]].map(([label,value])=><div key={String(label)}><span>{label}</span><b>{value??'—'}</b></div>)}<div className="customer-history"><h3>Purchase history</h3><div className="table-scroll"><table><thead><tr><th>Invoice / date</th><th>Items / IMEI</th><th>Total</th><th>Balance</th></tr></thead><tbody>{selectedInvoices.visible.map((s:Row)=><tr key={s.id}><td>{s.invoice_number}<small>{new Date(s.sale_date).toLocaleDateString('en-PK',{timeZone:'Asia/Karachi'})}</small></td><td>{data.saleItems.filter((i:Row)=>i.sale_id===s.id).map((i:Row)=><div key={i.id}>{i.item_name}{Number(i.quantity)>1?' × '+i.quantity:''}<small>{selected.phones.find((p:Row)=>p.id===i.id)?.phone?.imei_1||''}</small></div>)}</td><td>{money(s.final_total)}</td><td>{money(customerDue(s))}</td></tr>)}</tbody></table></div><Pagination {...selectedInvoices.pagination}/>{!selected.realSales.length&&<p>No recorded purchases yet.</p>}</div><div className="customer-history"><h3>Payment history</h3>{selectedPayments.visible.map((p:Row)=><p key={p.id}>{new Date(p.payment_date).toLocaleDateString('en-PK',{timeZone:'Asia/Karachi'})} · {String(p.method).replaceAll('_',' ')} · {money(p.amount)}</p>)}<Pagination {...selectedPayments.pagination}/>{!selected.paymentHistory.length&&<p>No payments recorded.</p>}</div></div><div className="actions"><button onClick={()=>setModal({action:'customer_edit',title:'Edit customer',item:selected,payload:{id:selected.id}})}>Edit customer</button><button onClick={()=>setModal({action:'statement',title:selected.full_name+' · Statement',contact:selected,isCustomer:true,records:selected.records})}>Statement / Receive payment</button><button disabled={!selected.mobile} onClick={()=>safe(async()=>whatsapp(selected.mobile,`Assalam u Alaikum ${selected.full_name}, thank you for choosing AppleSpace.`))}>WhatsApp</button></div></section>;
 return <><div className="info">Only customers with an outstanding balance appear here. Once fully paid, their records remain in Sales &amp; invoices and Customer messages.</div><div className="inventory-tabs" role="tablist" aria-label="Contact sections">{['customer','shopkeeper'].map(k=><button key={k} role="tab" aria-selected={kind===k} onClick={()=>{setKind(k);setSearch('');setDetail('')}}>{k==='customer'?'Customers':'Shopkeepers'}</button>)}</div><div className="toolbar"><input aria-label="Search customers" placeholder="Search name, phone or purchased phone" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Customer filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All outstanding customers</option><option value="recent">Purchased in last 30 days</option></select>{manager&&<button onClick={()=>setModal({action:'opening_receivable',title:'Add old pending balance',customerKind:kind})}>Add legacy balance</button>}</div><p>{shown.length} contacts · {money(contacts.reduce((n:number,c:Row)=>n+c.balance,0))} outstanding</p><div className="table-scroll"><table><thead><tr>{['Name','Phone','Phones purchased','Last purchase','Outstanding','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map((c:Row)=><tr key={c.id}><td><b>{c.full_name}</b></td><td>{c.mobile||'—'}</td><td>{c.phones.length?c.phones.map((p:Row)=>p.name).join(', '):'—'}</td><td>{c.last?new Date(c.last.sale_date).toLocaleDateString('en-PK',{timeZone:'Asia/Karachi'}):'—'}</td><td>{money(c.balance)}</td><td><div className="row-actions"><button onClick={()=>setDetail(c.id)}>Details</button><button onClick={()=>setModal({action:'statement',title:c.full_name+' · Statement',contact:c,isCustomer:true,records:c.records})}>Statement / Receive</button></div></td></tr>)}</tbody></table></div><Pagination {...pagination}/>{!shown.length&&<div className="empty"><p>No outstanding customers match this section.</p></div>}</>;
}
