import {useMemo,useState} from 'react';
import {Send} from 'lucide-react';
import {money} from './math.mjs';
import {customerHistory} from './customerHistory.mjs';
import {whatsapp} from './output';
type Row=Record<string,any>;
const templates:Record<string,string>={
 greeting:'Assalam u Alaikum {name}! AppleSpace wishes you a great day. Thank you for being part of our customer family.',
 deal:'Assalam u Alaikum {name}! We have new AppleSpace deals available. Reply here or visit us to check the latest iPhones and accessories.',
 update:'Assalam u Alaikum {name}! A quick AppleSpace update: {custom}',
 followup:'Assalam u Alaikum {name}! We hope you are enjoying your {last_phone}. If you need accessories, upgrades or any help, message AppleSpace anytime.'
};
export default function CustomerCRM({data,customerDue}:{data:Row;customerDue:(sale:Row)=>number}){
 const [audience,setAudience]=useState('all'),[template,setTemplate]=useState('deal'),[custom,setCustom]=useState(''),[search,setSearch]=useState(''),[draft,setDraft]=useState(templates.deal),[preview,setPreview]=useState('');
 const contacts=useMemo(()=>data.customers.map((c:Row)=>customerHistory(data,c)),[data]);
 const shown=contacts.filter((c:Row)=>{const matches=[c.full_name,c.mobile,...c.phones].some(v=>String(v||'').toLowerCase().includes(search.toLowerCase()));if(!matches)return false;if(audience==='customers')return (c.customer_kind||'customer')==='customer';if(audience==='shopkeepers')return c.customer_kind==='shopkeeper';if(audience==='outstanding')return c.balance>0;if(audience==='recent')return c.last&&Date.now()-new Date(c.last.sale_date).getTime()<30*86400000;return true});
 const message=(c:Row)=>draft.replaceAll('{name}',c.full_name||'Customer').replaceAll('{last_phone}',c.lastPhone).replaceAll('{custom}',custom||'New stock and updates are available.');
 return <div className="crm-grid"><section className="panel"><div className="panel-head"><div><h3>Message composer</h3><small>Greetings, deals, alerts and follow-ups</small></div></div><label className="field"><span>Audience</span><select value={audience} onChange={e=>setAudience(e.target.value)}><option value="all">All contacts</option><option value="customers">Customers only</option><option value="shopkeepers">Shopkeepers only</option><option value="recent">Bought in last 30 days</option><option value="outstanding">Outstanding balance</option></select></label><label className="field"><span>Message type</span><select value={template} onChange={e=>{setTemplate(e.target.value);setDraft(templates[e.target.value])}}><option value="greeting">Greeting</option><option value="deal">New deal / offer</option><option value="update">Update / alert</option><option value="followup">After-sale follow-up</option></select></label><label className="field"><span>Message text</span><textarea aria-label="Campaign message" value={draft} onChange={e=>setDraft(e.target.value)}/><small>Personalize with {'{name}'} or {'{last_phone}'}.</small></label>{template==='update'&&<label className="field"><span>Update text</span><textarea value={custom} onChange={e=>setCustom(e.target.value)} placeholder="Example: iPhone 16 Pro Max stock has arrived."/></label>}<div className="message-preview"><b>Message preview</b><p>{message(shown.find((c:Row)=>c.id===preview)||shown[0]||{full_name:'Customer',lastPhone:'phone'})}</p></div><div className="info">Messages open in WhatsApp one customer at a time so you can review before sending.</div></section><section className="panel"><div className="panel-head"><div><h3>Customer list</h3><small>{shown.length} matching contacts</small></div></div><div className="toolbar"><input placeholder="Search customer, phone or purchased model" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="table-scroll"><table><thead><tr><th>Name</th><th>Phone</th><th>Purchase history</th><th>Last purchase</th><th>Balance</th><th>Message</th></tr></thead><tbody>{shown.map((c:Row)=><tr key={c.id}><td><b>{c.full_name}</b><small>{c.customer_kind||'customer'}</small></td><td>{c.mobile||'—'}</td><td>{c.phones.length?c.phones.join(', '):'No software-era phone sale'}</td><td>{c.last?new Date(c.last.sale_date).toLocaleDateString('en-PK'):'—'}</td><td>{money(c.balance)}</td><td><button onClick={()=>setPreview(c.id)}>Preview</button><button disabled={!c.mobile} onClick={()=>whatsapp(c.mobile||'',message(c))}><Send size={15}/>WhatsApp</button></td></tr>)}</tbody></table></div></section></div>;
}
