import {useState} from 'react';
import {money} from './math.mjs';
import {whatsapp} from './output';
type Row=Record<string,any>;
export default function Customers({data,manager,setModal,customerDue,safe}:{data:Row;manager:boolean;setModal:(v:Row)=>void;customerDue:(r:Row)=>number;safe:(fn:()=>Promise<any>)=>Promise<any>}){
 const [kind,setKind]=useState('customer'),[filter,setFilter]=useState('unpaid'),[search,setSearch]=useState('');
 const contacts=data.customers.filter((c:Row)=>(c.customer_kind||'customer')===kind).map((c:Row)=>{const records=data.sales.filter((s:Row)=>s.customer_id===c.id);return {...c,records,balance:records.reduce((n:number,r:Row)=>n+customerDue(r),0)}});
 const shown=contacts.filter((c:Row)=>(filter==='all'||c.balance>0)&&[c.full_name,c.mobile,c.cnic].some(v=>String(v||'').toLowerCase().includes(search.toLowerCase())));
 return <><div className="inventory-tabs" role="tablist" aria-label="Contact sections">{['customer','shopkeeper'].map(k=><button key={k} role="tab" aria-selected={kind===k} onClick={()=>{setKind(k);setSearch('')}}>{k==='customer'?'Customers':'Shopkeepers'}</button>)}</div><div className="toolbar"><input aria-label="Search customers" placeholder="Search name or phone" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Customer balance filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="unpaid">Unpaid only</option><option value="all">All contacts</option></select>{manager&&<button onClick={()=>setModal({action:'opening_receivable',title:'Add old pending balance',customerKind:kind})}>Add old pending balance</button>}</div><p>{shown.length} contacts · {money(contacts.reduce((n:number,c:Row)=>n+c.balance,0))} outstanding</p><div className="table-scroll"><table><thead><tr>{['Name','Phone','Outstanding','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{shown.map((c:Row)=><tr key={c.id}><td><b>{c.full_name}</b></td><td>{c.mobile||'—'}</td><td>{money(c.balance)}</td><td><div className="row-actions"><button onClick={()=>setModal({action:'customer_edit',title:'Edit customer',item:c,payload:{id:c.id}})}>Edit</button><button onClick={()=>setModal({action:'statement',title:c.full_name+' · Statement',contact:c,isCustomer:true,records:c.records})}>Statement / Receive</button>{c.balance>0&&<button onClick={()=>safe(async()=>whatsapp(c.mobile||'',`Assalam u Alaikum ${c.full_name}, your outstanding AppleSpace balance is ${money(c.balance)}. Please contact us to arrange payment. Thank you.`))}>WhatsApp reminder</button>}</div></td></tr>)}</tbody></table></div>{!shown.length&&<div className="empty"><p>{filter==='unpaid'?'No unpaid contacts match this section.':'No contacts match this section.'}</p></div>}</>;
}
