import {money} from './math.mjs';
type Row=Record<string,any>;
export function ptaName(value:unknown){return ({non_pta:'Non-PTA',pta_approved:'PTA Approved',jv:'JV'} as Record<string,string>)[String(value)]||String(value||'Not recorded').replaceAll('_',' ')}
export function phoneDetails(item:Row,phones:Row[]){return item.phone_details&&Object.keys(item.phone_details).length?item.phone_details:phones.find(p=>p.id===item.inventory_item_id)||null}
const present=(v:unknown)=>v!=null&&String(v).trim()!=='';
export function phoneDetailLines(phone:Row|null,includeHealth=true){if(!phone)return [];return [present(phone.storage)?`Storage: ${phone.storage}`:'',present(phone.pta_status)?`PTA: ${ptaName(phone.pta_status)}`:'',present(phone.imei_1)?`IMEI: ${phone.imei_1}`:present(phone.serial_number)?`Serial: ${phone.serial_number}`:'',present(phone.imei_2)?`IMEI 2: ${phone.imei_2}`:'',includeHealth&&present(phone.battery_health)?`Battery health: ${phone.battery_health}%`:'',present(phone.color)?`Color: ${phone.color}`:'',present(phone.condition_grade)?`Condition: ${phone.condition_grade}`:'',present(phone.warranty_notes)?`Warranty: ${phone.warranty_notes}`:''].filter(Boolean)}
export function invoicePhoneDetailLines(phone:Row|null){return phoneDetailLines(phone,false).map(line=>line.replace(/^PTA: /,''))}
export function paymentLines(payments:Row[],label='Received'){const groups=new Map<string,number>();for(const p of payments){const amount=Number(p.amount);if(amount>0)groups.set(p.method||'cash',(groups.get(p.method||'cash')||0)+amount);}return [...groups].map(([method,amount])=>`${label} by ${({cash:'Cash',bank_transfer:'Bank transfer',card:'Card',jazzcash:'JazzCash',easypaisa:'EasyPaisa'} as Record<string,string>)[method]||method}: ${money(amount)}`)}
export function receivableReminder(entry:Row){return `Dear ${entry.person},\nYour outstanding balance with AppleSpace is ${money(entry.balance)}${entry.reference?' ('+entry.reference+')':''}. Please arrange payment at your convenience.\nThank you, AppleSpace.`}
export function invoiceMessage(sale:Row,items:Row[],payments:Row[],customer:Row|undefined,phones:Row[]){
 const lines=items.filter(i=>i.sale_id===sale.id).flatMap(i=>{const phone=phoneDetails(i,phones);return [`${phone?.model||i.item_name}${Number(i.quantity)>1?' × '+i.quantity:''} — ${i.price_visible===false?'Included':money(i.final_price)}`,...invoicePhoneDetailLines(phone)];});
 const paid=payments.filter(p=>p.sale_id===sale.id).reduce((s,p)=>s+Number(p.amount),0);
 return [`AppleSpace ${sale.is_opening_balance?'balance receipt':'invoice'} ${sale.invoice_number}`,new Date(sale.sale_date).toLocaleString('en-PK',{timeZone:'Asia/Karachi'}),`Customer: ${customer?.full_name||'Walk-in'}`,`Bill made by: ${sale.billed_by_name||'Staff'}`,...(sale.is_opening_balance?[`Prior record: ${sale.opening_reference||''}`]:[]),'',...lines,'',`Total: ${money(sale.final_total)}`,`Received: ${money(paid)}`,...paymentLines(payments.filter(p=>p.sale_id===sale.id)),`Balance: ${money(Math.max(0,Number(sale.final_total)-paid))}`,'Thank you for choosing AppleSpace.'].join('\n');
}
