import {useDeferredValue,useMemo,useRef,useState} from 'react';
import Pagination,{usePagination} from './Pagination';
import type {FormEvent} from 'react';
import {Plus,Download,Printer} from 'lucide-react';
import {money,localDay,sum} from './math.mjs';
import {ledgerCategories,ledgerRows} from './ledger.mjs';
import {receivableReminder} from './invoiceDetails';
import {exportRows,printReport,whatsapp} from './outputActions';
type Row=Record<string,any>;
type Props={kind:'receivable'|'payable';data:Row;manager:boolean;save:(payload:Row)=>Promise<void>;setModal:(modal:Row)=>void};
export default function LedgerPage({kind,data,manager,save,setModal}:Props){
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('outstanding'),[add,setAdd]=useState(false),[category,setCategory]=useState('existing_balance'),[recordDate,setRecordDate]=useState(localDay(new Date())),[detail,setDetail]=useState(''),[pay,setPay]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const working=useRef(false),rows=useMemo(()=>ledgerRows(data,kind),[data,kind]),title=kind==='receivable'?'Receivables ledger':'Payables ledger',receive=kind==='receivable';
 const query=useDeferredValue(search).toLowerCase();
 const shown=useMemo(()=>rows.filter(r=>(filter==='all'||r.balance>0||r.costPending)&&[r.person,r.phone,r.reference,r.description,r.type].some(v=>String(v||'').toLowerCase().includes(query))),[rows,filter,query]);
 const {visible,pagination}=usePagination(shown,kind+filter+query);
 const selected=rows.find(r=>r.source+':'+r.id===detail),target=rows.find(r=>r.source+':'+r.id===pay);
 const exported=()=>shown.map(r=>({Name:r.person,Phone:r.phone||'',Type:r.type,Reference:r.reference,Date:r.date,Description:r.description,Total:r.costPending?'Cost pending':r.total,Paid:r.paid,Outstanding:r.costPending?'Cost pending':r.balance}));
 if(!manager)return <div className="info">Owner or manager access is required for this ledger.</div>;
 async function run(fn:()=>Promise<void>){if(working.current)return;working.current=true;setBusy(true);setError('');setNotice('');try{await fn()}catch(e:any){setError(e.message||'Could not save the ledger change.')}finally{working.current=false;setBusy(false)}}
 function addEntry(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));run(async()=>{await save({...values,action:'ledger_entry',kind});setAdd(false);setCategory('existing_balance');setNotice('Balance added to the ledger.');});}
 function payEntry(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!target)return;const values=Object.fromEntries(new FormData(e.currentTarget));run(async()=>{await save({...values,action:'ledger_payment',entry_id:target.id});setPay('');setNotice(receive?'Receipt saved.':'Payment saved.');});}
 const categories=receive?['existing_balance','money_advance','service_income']:['existing_balance','money_borrowed','expense_owed'];
 const settle=(r:Row)=>{if(r.source==='manual'){setPay(r.source+':'+r.id);setDetail('');setAdd(false)}else setModal({action:receive?'customer_payment':'supplier_payment',title:receive?'Receive payment':'Pay supplier',balance:r.balance,payload:{[receive?'sale_id':'purchase_id']:r.id}})};
 return <div className="ledger-page"><div className="ledger-summary"><div><span>Total outstanding</span><strong>{money(sum(rows,'balance'))}</strong></div><div><span>Unpaid records</span><strong>{rows.filter(r=>r.balance>0).length}</strong></div><button className="primary" disabled={busy} onClick={()=>{setAdd(!add);setPay('');setError('')}}><Plus size={17}/>{receive?'Add other receivable':'Add other payable'}</button></div>
 <div className="info">This ledger includes {receive?'sales invoices and customer balances':'stock purchases and supplier balances'}, plus other amounts owed. Add loans, advances, services or existing balances without creating a phone transaction.</div>
 {error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="info" role="status">{notice}</div>}
 {add&&<section className="panel ledger-card"><h3>{receive?'Add receivable':'Add payable'}</h3><form onSubmit={addEntry}><div className="form-grid"><label className="field"><span>Person / business name *</span><input name="full_name" required maxLength={200}/></label><label className="field"><span>Phone (optional)</span><input name="mobile" type="tel" maxLength={25}/></label><label className="field"><span>What does this balance represent? *</span><select name="category" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option value={c} key={c}>{ledgerCategories[c]}</option>)}</select></label><label className="field"><span>Amount *</span><input name="amount" type="number" min="0.01" step="0.01" required/></label><label className="field"><span>Record date *</span><input name="record_date" type="date" value={recordDate} max={localDay(new Date())} onChange={e=>setRecordDate(e.target.value)} required/></label><label className="field"><span>Due date (optional)</span><input name="due_date" type="date" min={recordDate}/></label><label className="field"><span>Reference (optional)</span><input name="reference" maxLength={120}/></label><label className="field"><span>Description (optional)</span><input name="description" maxLength={1000}/></label>{['money_advance','money_borrowed'].includes(category)&&<Method label={receive?'Money advanced through':'Money received through'}/>}<label className="field"><span>Notes (optional)</span><input name="notes" maxLength={2000}/></label></div><p>{category==='existing_balance'?'Records an existing amount owed without adding sales, expenses or a cash movement.':category==='money_advance'?'Records money lent or advanced and reduces the selected cash/bank balance.':category==='money_borrowed'?'Records borrowed money and increases the selected cash/bank balance.':category==='service_income'?'Records other income owed to you. Record associated costs in Expenses.':'Records an unpaid expense; cash decreases when you pay it.'}</p><div className="actions"><button className="primary" disabled={busy}>{busy?'Saving…':'Save balance'}</button><button type="button" disabled={busy} onClick={()=>setAdd(false)}>Cancel</button></div></form></section>}
 {target&&target.balance>0&&<section className="panel ledger-card"><h3>{receive?'Receive from':'Pay'} {target.person}</h3><p>{target.description} · Outstanding {money(target.balance)}</p><form onSubmit={payEntry}><div className="form-grid"><label className="field"><span>{receive?'Received amount':'Paid amount'} *</span><input name="amount" type="number" min="0.01" max={target.balance} step="0.01" defaultValue={target.balance} required/></label><Method/><label className="field"><span>Notes (optional)</span><input name="notes" maxLength={2000}/></label></div><div className="actions"><button className="primary" disabled={busy}>{busy?'Saving…':receive?'Save receipt':'Save payment'}</button><button type="button" disabled={busy} onClick={()=>setPay('')}>Cancel</button></div></form></section>}
 <section className="panel"><div className="toolbar"><input aria-label="Search ledger" placeholder="Search name, reference or description" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Ledger filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="outstanding">Outstanding only</option><option value="all">All records / history</option></select><button disabled={busy||!shown.length} onClick={()=>run(async()=>{await exportRows(title,exported(),'xlsx')})}><Download size={16}/>Excel</button><button disabled={!shown.length} onClick={()=>run(()=>printReport(title,exported()))}><Printer size={16}/>Print / PDF</button></div><div className="table-scroll"><table><thead><tr>{['Name','Type / reference','Description','Date / due','Total','Paid','Outstanding','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.source+':'+r.id}><td><b>{r.person}</b><small>{r.phone||'—'}</small></td><td>{r.type}<small>{r.reference}</small></td><td>{r.description}</td><td>{r.date}<small>{r.due_date?'Due '+r.due_date:''}</small></td><td>{r.costPending?'Cost pending':money(r.total)}</td><td>{money(r.paid)}</td><td>{r.costPending?'Cost pending':r.balance>0?<b>{money(r.balance)}</b>:<span className="tag paid">Settled</span>}</td><td><div className="row-actions"><button onClick={()=>setDetail(detail===r.source+':'+r.id?'':r.source+':'+r.id)}>History</button>{receive&&r.balance>0&&<button title={r.phone?'Open outstanding balance reminder in WhatsApp':'Add a phone number to send a reminder'} disabled={busy||!r.phone} onClick={()=>run(async()=>{whatsapp(r.phone,receivableReminder(r));setNotice('Reminder opened in WhatsApp. Review it and press Send.');})}>Remind on WhatsApp</button>}{r.balance>0&&<button disabled={busy} onClick={()=>settle(r)}>{receive?'Receive':'Pay'}</button>}</div></td></tr>)}</tbody></table></div><Pagination {...pagination}/>{!shown.length&&<div className="empty">No {filter==='outstanding'?'outstanding ':''}records match this ledger.</div>}</section>
 {selected&&<section className="panel ledger-card"><div className="panel-head"><h3>{selected.person} · Payment history</h3><button onClick={()=>setDetail('')}>Close</button></div><p>{selected.reference} · {selected.description}</p>{selected.payments.length?<div className="table-scroll"><table><thead><tr><th>Date</th><th>Method</th><th>Amount</th><th>Notes</th></tr></thead><tbody>{selected.payments.map((p:Row)=><tr key={p.id}><td>{localDay(p.payment_date)}</td><td>{String(p.method).replaceAll('_',' ')}</td><td>{money(p.amount)}</td><td>{p.notes||'—'}</td></tr>)}</tbody></table></div>:<p>No payments yet.</p>}</section>}
 </div>;
}
function Method({label='Payment method'}:{label?:string}){return <label className="field"><span>{label}</span><select name="method"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="jazzcash">JazzCash</option><option value="easypaisa">EasyPaisa</option></select></label>}
