import {due,localDay,sum} from './math.mjs';
import {purchaseHistory} from './purchaseHistory.mjs';
import {storeIndex} from './storeIndex.mjs';
export const ledgerCategories={existing_balance:'Existing balance',money_advance:'Money lent / advance',service_income:'Other service income owed',money_borrowed:'Money borrowed / received',expense_owed:'Expense owed'};
export function ledgerRows(data,kind){
 const index=storeIndex(data);if(index.ledgers.has(kind))return index.ledgers.get(kind);
 const manual=(data.ledgerEntries||[]).filter(e=>e.kind===kind).map(e=>{const payments=index.paymentsByEntry.get(e.id)||[];const balance=due(e,payments,'entry_id','amount');return {...e,source:'manual',person:e.full_name,phone:e.mobile,date:e.record_date,reference:e.reference||'Other balance',total:Number(e.amount),balance,paid:Number(e.amount)-balance,payments,type:ledgerCategories[e.category],costPending:false};});
 const automatic=kind==='receivable'?(data.sales||[]).map(s=>{const c=index.customers.get(s.customer_id);const payments=index.paymentsBySale.get(s.id)||[];const balance=due(s,payments,'sale_id','final_total');return {id:s.id,source:'sale',person:c?.full_name||'Walk-in',phone:c?.mobile,date:localDay(s.sale_date),reference:s.is_opening_balance?s.opening_reference:s.invoice_number,description:s.is_opening_balance?'Opening customer balance':(index.itemsBySale.get(s.id)||[]).map(i=>i.item_name).join(', '),total:Number(s.final_total),balance,paid:Number(s.final_total)-balance,payments,type:s.is_opening_balance?'Customer opening balance':'Sales invoice',costPending:false};}):(data.purchases||[]).map(p=>{const h=purchaseHistory(data,p);return {id:p.id,source:'purchase',person:h.seller?.full_name||'Unknown seller',phone:h.seller?.mobile,date:localDay(p.purchase_date),reference:'#'+p.purchase_number,description:h.model||p.notes||'Stock purchase',total:Number(p.total_amount),balance:h.payable,paid:Number(p.total_amount)-h.payable,payments:index.paymentsByPurchase.get(p.id)||[],type:'Stock purchase',costPending:h.costPending};});
 const result=[...automatic,...manual].sort((a,b)=>b.date.localeCompare(a.date));index.ledgers.set(kind,result);return result;
}
export function ledgerImpact(data,period=()=>true){const entries=(data.ledgerEntries||[]).filter(e=>period(e.record_date));return {income:sum(entries.filter(e=>e.category==='service_income'),'amount'),expenses:sum(entries.filter(e=>e.category==='expense_owed'),'amount')};}
export const ownerPages=['Reports','Daily closing','Record cleanup','Settings'];
export function pageAllowed(page,role){if(ownerPages.includes(page))return role==='owner';if(['Purchases','Suppliers','Expenses','Settings','Receivables ledger','Payables ledger'].includes(page))return role==='owner'||role==='manager';return ['owner','manager','salesperson'].includes(role);}
