import JsBarcode from 'jsbarcode';
import QRCode from 'qrcode';
import {money} from './math.mjs';
import {phoneDetails,phoneDetailLines,ptaName,invoiceMessage} from './invoiceDetails';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function download(name:string,data:BlobPart,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export async function exportRows(name:string,rows:any[],format:'csv'|'xlsx'){
 if(!rows.length)throw Error('No records to export.');
 const keys=Object.keys(rows[0]).filter(k=>typeof rows[0][k]!=='object');
 if(format==='csv'){const quote=(v:any)=>{let s=String(v??'');if(typeof v==='string'&&/^[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};download(name+'.csv',[keys.join(','),...rows.map(r=>keys.map(k=>quote(r[k])).join(','))].join('\r\n'),'text/csv');return;}
 const ExcelJS=await import('exceljs');const book=new ExcelJS.Workbook();const sheet=book.addWorksheet(name.slice(0,31));sheet.columns=keys.map(k=>({header:k,key:k,width:23}));rows.forEach(r=>sheet.addRow(Object.fromEntries(keys.map(k=>[k,r[k]??'']))));sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF176F60'}};const data=await book.xlsx.writeBuffer();download(name+'.xlsx',data as BlobPart,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
}
function printHTML(html:string,title:string,extraCSS=''){const frame=document.createElement('iframe');frame.style.cssText='position:fixed;width:0;height:0;border:0';document.body.append(frame);const doc=frame.contentDocument!;doc.open();doc.write(`<!doctype html><html><head><title>${esc(title)}</title><style>body{font:14px Arial;color:#192824;margin:35px}${localStorage.getItem('invoice-template')==='receipt'?'body{width:72mm;margin:0}body h1{font-size:24px}body td,body th{padding:6px;font-size:10px}body small{font-size:9px}body .total{font-size:13px}':''}h1{font-size:30px;margin:0}h2{font-size:22px}small{color:#66736e}table{width:100%;border-collapse:collapse;margin:24px 0}td,th{text-align:left;padding:12px;border-bottom:1px solid #ddd}.total{text-align:right;font-size:18px}img{max-width:100%}.label{width:62mm;text-align:center;border:1px dashed #aaa;padding:3mm;page-break-inside:avoid}.label svg{width:56mm}.label img{width:20mm}@page{margin:12mm}${extraCSS}</style></head><body>${html}</body></html>`);doc.close();Promise.all([...doc.images].map(i=>i.complete?Promise.resolve():new Promise<void>(resolve=>{i.onload=()=>resolve();i.onerror=()=>resolve()}))).then(()=>{frame.contentWindow!.focus();frame.contentWindow!.print();setTimeout(()=>frame.remove(),60000)});}
export async function printLabel(item:any,{accessory=false,copies=1,includeHealth=true}:{accessory?:boolean;copies?:number;includeHealth?:boolean}={}){
 if(!Number.isInteger(copies)||copies<1||copies>500)throw Error('Choose 1 to 500 labels.');
 const code=accessory?item.sku:item.imei_1||item.serial_number||item.barcode_value||item.stock_code;if(!code)throw Error('No label code is available for this item.');
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');JsBarcode(svg,String(code),{format:'CODE128',height:24,width:1.2,displayValue:false,margin:4});
 const qr=await QRCode.toDataURL(String(code),{margin:4,width:160,errorCorrectionLevel:'M'});
 const details=accessory?esc(item.category):`${esc(ptaName(item.pta_status))}${includeHealth&&item.battery_health!=null?' · Health '+esc(item.battery_health)+'%':''}`;
 const label=`<div class="stock-label"><b>AppleSpace</b><div class="label-model">${esc(item.model||item.name)}${!accessory&&item.storage?' · '+esc(item.storage):''}</div><div>${details}</div><div class="label-code">${accessory?'SKU':'IMEI / Serial'}: ${esc(code)}</div>${!accessory&&item.imei_2?`<div class="label-code">IMEI 2: ${esc(item.imei_2)}</div>`:''}<div class="label-symbols"><div><span>Barcode</span>${svg.outerHTML}</div><div><span>QR</span><img src="${qr}"/></div></div></div>`;
 printHTML(Array(copies).fill(label).join(''),accessory?'Accessory labels':'Phone labels',`@page{size:50mm 30mm;margin:0}body{margin:0;width:50mm;font:7pt Arial;color:#000}.stock-label{box-sizing:border-box;width:50mm;height:30mm;padding:1.5mm;break-after:page;overflow:hidden;text-align:center}.stock-label:last-child{break-after:auto}.stock-label b{font-size:8pt}.label-model{font-weight:bold;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.label-code{font-size:6.5pt}.label-symbols{display:flex;justify-content:center;align-items:start;gap:2mm;margin-top:.5mm}.label-symbols span{display:block;font-size:5pt}.label-symbols svg{width:31mm;height:8mm}.label-symbols img{width:10mm;height:10mm}`);
}
export function printInvoice(sale:any,items:any[],payments:any[],customer:any,phones:any[]){const paid=payments.filter(p=>p.sale_id===sale.id).reduce((s,p)=>s+Number(p.amount),0);printHTML(`<h1>AppleSpace</h1><small>Shop 103 & 104, Mezzanine Floor, Noor Mobile Mall, 6th Road, Rawalpindi<br/>WhatsApp +92 334 5136382</small><h2>${sale.is_opening_balance?'Settled balance receipt':'Sales invoice'}</h2>${sale.is_opening_balance?`<p>Prior record: ${esc(sale.opening_reference)}</p>`:''}<p>${sale.sale_kind==='shopkeeper'?'Shopkeeper sale':'Customer sale'} · Bill made by: ${esc(sale.billed_by_name||'Staff')}</p><p>${esc(sale.invoice_number)} · ${esc(new Date(sale.sale_date).toLocaleString('en-PK',{timeZone:'Asia/Karachi'}))}</p><p>Customer: ${esc(customer?.full_name||'Walk-in')}<br/>${esc(customer?.mobile||'')}</p><table><tr><th>Phone / IMEI</th><th>Price</th><th>Discount</th><th>Total</th></tr>${items.filter(i=>i.sale_id===sale.id).map(i=>`<tr><td>${esc(phoneDetails(i,phones)?.model||i.item_name)}${Number(i.quantity)>1?` × ${esc(i.quantity)}`:''}<br/><small>${phoneDetailLines(phoneDetails(i,phones)).map(esc).join('<br/>')}</small></td><td>${i.price_visible===false?'Included':money(i.unit_price)}</td><td>${i.price_visible===false?'—':money(i.discount)}</td><td>${i.price_visible===false?'—':money(i.final_price)}</td></tr>`).join('')}</table><div class="total">${sale.is_opening_balance?'Opening balance':'Total'}: ${money(sale.final_total)}<br/>Received: ${money(paid)}<br/><b>Balance: ${money(Number(sale.final_total)-paid)}</b></div><small>Thank you for choosing AppleSpace.</small>`,sale.invoice_number);}
export function printSlip(purchase:any,items:any[],supplier:any,payments:any[]){const paid=payments.filter(p=>p.purchase_id===purchase.id).reduce((s,p)=>s+Number(p.amount),0);printHTML(`<h1>AppleSpace</h1><h2>Purchase slip #${esc(purchase.purchase_number)}</h2><p>${esc(supplier?.full_name)} · ${esc(supplier?.mobile)}<br/>${esc(supplier?.cnic)}</p><table><tr><th>Phone</th><th>IMEI / Serial</th><th>Cost</th></tr>${items.filter(i=>i.purchase_id===purchase.id).map(i=>`<tr><td>${esc(i.model)}</td><td>${esc(i.imei_1||i.serial_number)}</td><td>${money(i.purchase_price)}</td></tr>`).join('')}</table><p>Total: ${money(purchase.total_amount)}<br/>Paid: ${money(paid)}<br/>Payable: ${money(Number(purchase.total_amount)-paid)}</p>`,'Purchase slip');}
export function printReport(title:string,rows:any[]){const keys=rows.length?Object.keys(rows[0]).filter(k=>typeof rows[0][k]!=='object'):[];printHTML(`<h1>AppleSpace</h1><h2>${esc(title)}</h2><small>Generated ${esc(new Date().toLocaleString('en-PK',{timeZone:'Asia/Karachi'}))}</small><table><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join('')}</tr>${rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')}</table>`,title);}
export function whatsapp(phone:string,text:string){let n=phone.replace(/\D/g,'');if(n.startsWith('0'))n='92'+n.slice(1);if(!n)throw Error('Add a customer phone number first.');window.open(`https://wa.me/${n}?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer');}
export async function invoicePDF(sale:any,items:any[],payments:any[],customer:any,phones:any[]){
 const {PDFDocument,StandardFonts,rgb}=await import('pdf-lib');const pdf=await PDFDocument.create();let page=pdf.addPage([595.28,841.89]);const font=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);const clean=(v:any)=>String(v??'').replace(/[^\x20-\x7E\xA0-\xFF]/g,'?');const draw=(s:string,x:number,y:number,size=11,strong=false)=>page.drawText(clean(s),{x,y,size,font:strong?bold:font,color:rgb(.12,.22,.17)});
 draw('AppleSpace',42,782,29,true);draw(sale.is_opening_balance?'SETTLED BALANCE RECEIPT':'SALES INVOICE',42,746,13,true);draw('Shop 103 & 104, Noor Mobile Mall, 6th Road, Rawalpindi',42,721,10);draw('WhatsApp +92 334 5136382',42,704,10);draw(sale.invoice_number,42,661,12,true);draw(dateForPDF(sale.sale_date),350,661,10);draw('Customer: '+(customer?.full_name||'Walk-in'),42,632);draw(customer?.mobile||'',42,615);draw('Bill made by: '+(sale.billed_by_name||'Staff'),42,595,10);let y=552;if(sale.is_opening_balance){draw(('Prior record: '+(sale.opening_reference||'')).slice(0,70),42,575,10);}draw('Phone / IMEI',42,y,11,true);draw('Final amount',420,y,11,true);y-=30;
 for(const i of items.filter(i=>i.sale_id===sale.id)){const phone=phoneDetails(i,phones),details=phoneDetailLines(phone);if(y<180+details.length*15){page=pdf.addPage([595.28,841.89]);y=780;draw('AppleSpace - '+sale.invoice_number,42,y,12,true);y-=35;}draw(((phone?.model||i.item_name)+(Number(i.quantity)>1?' x '+i.quantity:'')).slice(0,48),42,y,11,true);draw(i.price_visible===false?'Included':money(i.final_price),420,y,11);y-=20;for(const detail of details){draw(detail.slice(0,70),42,y,10);y-=15;}y-=20;}
 if(y<180){page=pdf.addPage([595.28,841.89]);y=780;draw('AppleSpace - '+sale.invoice_number,42,y,12,true);y-=35;}
 const paid=payments.filter(p=>p.sale_id===sale.id).reduce((s,p)=>s+Number(p.amount),0);y-=20;for(const [label,value] of [[sale.is_opening_balance?'Opening balance':'Total',sale.final_total],['Received',paid],['Balance',Number(sale.final_total)-paid]] as const){draw(label,350,y,12,true);draw(money(value),420,y,12,true);y-=23;}draw('Thank you for choosing AppleSpace.',42,80,10);
 return new File([new Uint8Array(await pdf.save())],sale.invoice_number+'.pdf',{type:'application/pdf'});
}
const dateForPDF=(v:string)=>new Date(v).toLocaleString('en-PK',{timeZone:'Asia/Karachi'});
export async function shareInvoice(sale:any,items:any[],payments:any[],customer:any,phones:any[]){const file=await invoicePDF(sale,items,payments,customer,phones);if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'AppleSpace invoice '+sale.invoice_number});}else{download(file.name,await file.arrayBuffer(),'application/pdf');whatsapp(customer?.mobile||'',`AppleSpace invoice ${sale.invoice_number}\nTotal: ${money(sale.final_total)}\nYour invoice PDF is ready. Thank you for choosing AppleSpace.`);}}

export function sendInvoiceWhatsApp(sale:any,items:any[],payments:any[],customer:any,phones:any[]){whatsapp(customer?.mobile||'',invoiceMessage(sale,items,payments,customer,phones));}
