import {download} from './browserActions';
export {download,whatsapp,whatsappNumber,canShareInvoicePDF,sendInvoiceWhatsApp} from './browserActions';
import JsBarcode from 'jsbarcode';
import QRCode from 'qrcode';
import {ptaName} from './invoiceDetails';
import {saleFormPages,purchaseFormPages,formsHTML,formsCSS,formsPDF,printablePhoto} from './documentForms';
import {labelCSS,defaultLabelSize,type LabelSize} from './labelLayout';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function exportRows(name:string,rows:any[],format:'csv'|'xlsx'){
 if(!rows.length)throw Error('No records to export.');
 const keys=Object.keys(rows[0]).filter(k=>typeof rows[0][k]!=='object');
 if(format==='csv'){const quote=(v:any)=>{let s=String(v??'');if(typeof v==='string'&&/^[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};download(name+'.csv',[keys.join(','),...rows.map(r=>keys.map(k=>quote(r[k])).join(','))].join('\r\n'),'text/csv');return;}
 const ExcelJS=await import('exceljs');const book=new ExcelJS.Workbook();const sheet=book.addWorksheet(name.slice(0,31));sheet.columns=keys.map(k=>({header:k,key:k,width:23}));rows.forEach(r=>sheet.addRow(Object.fromEntries(keys.map(k=>[k,r[k]??'']))));sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF176F60'}};const data=await book.xlsx.writeBuffer();download(name+'.xlsx',data as BlobPart,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
}
function printHTML(html:string,title:string,extraCSS=''){const defer=setTimeout;const frame=document.createElement('iframe');frame.style.cssText='position:fixed;width:0;height:0;border:0';document.body.append(frame);const doc=frame.contentDocument!;doc.open();doc.write(`<!doctype html><html><head><title>${esc(title)}</title><style>body{font:14px Arial;color:#192824;margin:35px}${localStorage.getItem('invoice-template')==='receipt'?'body{width:72mm;margin:0}body h1{font-size:24px}body td,body th{padding:6px;font-size:10px}body small{font-size:9px}body .total{font-size:13px}':''}h1{font-size:30px;margin:0}h2{font-size:22px}small{color:#66736e}table{width:100%;border-collapse:collapse;margin:24px 0}td,th{text-align:left;padding:12px;border-bottom:1px solid #ddd}.total{text-align:right;font-size:18px}img{max-width:100%}.label{width:62mm;text-align:center;border:1px dashed #aaa;padding:3mm;page-break-inside:avoid}.label svg{width:56mm}.label img{width:20mm}@page{margin:12mm}${extraCSS}</style></head><body>${html}</body></html>`);doc.close();const fontReady=extraCSS.includes('AppleSpaceForm')&&doc.fonts?Promise.all([doc.fonts.load('12px AppleSpaceForm'),doc.fonts.load('bold 12px AppleSpaceForm')]).catch(()=>[]):Promise.resolve();Promise.all([fontReady,doc.fonts?.ready||Promise.resolve(),...[...doc.images].map(i=>i.complete?Promise.resolve():new Promise<void>(resolve=>{i.onload=()=>resolve();i.onerror=()=>resolve()}))]).then(()=>{frame.contentWindow!.focus();frame.contentWindow!.print();defer(()=>frame.remove(),60000)});}
export async function printLabel(item:any,{accessory=false,copies=1,includeHealth=true,size=defaultLabelSize}:{accessory?:boolean;copies?:number;includeHealth?:boolean;size?:LabelSize}={}){
 if(!Number.isInteger(copies)||copies<1||copies>500)throw Error('Choose 1 to 500 labels.');
 const css=labelCSS(size);
 const code=accessory?item.sku:item.imei_1||item.serial_number||item.barcode_value||item.stock_code;if(!code)throw Error('No label code is available for this item.');
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');JsBarcode(svg,String(code),{format:'CODE128',height:32,width:1,displayValue:false,margin:0,marginLeft:10,marginRight:10});svg.setAttribute('preserveAspectRatio','none');
 const qr=await QRCode.toDataURL(String(code),{margin:4,scale:6,errorCorrectionLevel:'M'});
 const details=accessory?esc(item.category):`${item.pta_status?esc(ptaName(item.pta_status)):''}${includeHealth&&item.battery_health!=null&&String(item.battery_health).trim()!==''?(item.pta_status?' · ':'')+'Health '+esc(item.battery_health)+'%':''}`;
 const label=`<div class="stock-label"><div class="label-top"><div class="label-details"><b>AppleSpace</b><div class="label-model">${esc(item.model||item.name)}${!accessory&&item.storage?' · '+esc(item.storage):''}</div><div class="label-status">${details}</div><div class="label-code">${accessory?'SKU':item.imei_1?'IMEI':'Serial'}: ${esc(code)}</div>${!accessory&&item.imei_2?`<div class="label-code">IMEI 2: ${esc(item.imei_2)}</div>`:''}</div><div class="label-qr"><img src="${qr}" alt="QR code for ${esc(code)}"/><span>QR</span></div></div><div class="label-barcode"><span>Barcode</span>${svg.outerHTML}</div></div>`;
 printHTML(Array(copies).fill(label).join(''),accessory?'Accessory labels':'Phone labels',css);
}
export function printInvoice(sale:any,items:any[],payments:any[],customer:any,phones:any[]){printHTML(formsHTML(saleFormPages(sale,items,payments,customer,phones)),sale.invoice_number,formsCSS);}
export async function printSlip(purchase:any,items:any[],supplier:any,payments:any[],accessories:any[]=[]){const seller={...supplier};if(seller.print_photo_url)seller.print_photo_url=await printablePhoto(seller.print_photo_url);printHTML(formsHTML(purchaseFormPages(purchase,items,seller,payments,accessories)),'Purchase slip #'+purchase.purchase_number,formsCSS);}
export async function purchaseSlipPDF(purchase:any,items:any[],supplier:any,payments:any[],accessories:any[]=[]){const seller={...supplier};if(seller.print_photo_url)seller.print_photo_url=await printablePhoto(seller.print_photo_url);return formsPDF(purchaseFormPages(purchase,items,seller,payments,accessories),'AppleSpace-purchase-'+purchase.purchase_number);}
export function printReport(title:string,rows:any[]){const keys=rows.length?Object.keys(rows[0]).filter(k=>typeof rows[0][k]!=='object'):[];printHTML(`<h1>AppleSpace</h1><h2>${esc(title)}</h2><small>Generated ${esc(new Date().toLocaleString('en-PK',{timeZone:'Asia/Karachi'}))}</small><table><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join('')}</tr>${rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')}</table>`,title);}
export async function invoicePDF(sale:any,items:any[],payments:any[],customer:any,phones:any[]){return formsPDF(saleFormPages(sale,items,payments,customer,phones),sale.invoice_number);}
