import {useDeferredValue,useMemo} from 'react';
import Pagination,{usePagination} from './Pagination';
import {Download,Printer,Pencil,Trash2} from 'lucide-react';
import {money} from './math.mjs';
import {purchaseHistory} from './purchaseHistory.mjs';
type Row=Record<string,any>;
type Props={data:Row;search:string;setSearch:(s:string)=>void;setModal:(v:Row)=>void;print:(purchase:Row,seller:Row|undefined,format?:'print'|'pdf')=>unknown;exportRows:(rows:Row[])=>void;removePurchase:(purchase:Row)=>void};
export default function Purchases({data,search,setSearch,setModal,print,exportRows,removePurchase}:Props){
 const all=useMemo(()=>data.purchases.map((p:Row)=>purchaseHistory(data,p)),[data]);
 const query=useDeferredValue(search).toLowerCase();
 const shown=useMemo(()=>all.filter((p:Row)=>[...Object.values(p),p.seller?.full_name,p.model,p.imei].some(v=>typeof v!=='object'&&String(v??'').toLowerCase().includes(query))),[all,query]);
 const {visible,pagination}=usePagination<Row>(shown,query);
 const exported=()=>shown.map((p:Row)=>({Purchase:p.purchase_number,Seller:p.seller?.full_name||'',Date:p.purchase_date,Model:p.model,IMEI:p.imei,Total:Number(p.total_amount),Payable:p.payable,CostPending:p.costPending}));
 return <section className="panel"><div className="toolbar"><input aria-label="Search purchases" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search seller, IMEI, model or purchase…"/><div className="toolbar-actions"><button onClick={()=>exportRows(exported())}><Download size={16}/>Excel</button></div></div><div className="info">Earlier purchases without payment records show as unpaid. Reconcile these balances before relying on financial reports.</div>{all.length?<div className="table-scroll"><table><thead><tr>{['Purchase','Seller name','IMEI','Model','Date','Total','Payable','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map((p:Row)=><tr key={p.id}><td><b>#{p.purchase_number}</b></td><td>{p.seller?.full_name||'—'}</td><td>{p.phones.length?p.phones.map((i:Row)=><div key={i.id}>{i.imei_1||i.serial_number||'—'}{i.imei_2&&<small>IMEI 2: {i.imei_2}</small>}</div>):'—'}</td><td>{p.phones.map((i:Row)=><div key={i.id}>{i.model}<small>{i.storage||''}</small></div>)}{p.accessories.map((i:Row)=><div key={i.id}>{i.name}<small>Accessory</small></div>)}{!p.model&&'—'}</td><td>{new Date(p.purchase_date).toLocaleDateString('en-PK',{timeZone:'Asia/Karachi'})}</td><td>{p.costPending?'Cost pending':money(p.total_amount)}</td><td>{p.costPending?'—':p.payable>0?<b>{money(p.payable)}</b>:<span className="tag paid">Paid</span>}</td><td><div className="row-actions"><button title="Print purchase slip" onClick={()=>print(p,p.seller)}><Printer size={16}/></button><button title="Download purchase slip PDF" onClick={()=>print(p,p.seller,'pdf')}><Download size={16}/></button>{p.phones.filter((i:Row)=>i.status!=='sold').map((i:Row)=><button key={i.id} title="Edit purchase" onClick={()=>setModal({action:'purchase_edit',title:'Edit purchase · '+i.model,item:i,purchase:p,seller:p.seller,payload:{purchase_id:p.id,inventory_id:i.id}})}><Pencil size={15}/>Edit purchase</button>)}{p.phones.some((i:Row)=>i.status!=='sold')&&<button className="danger-outline" title="Delete purchase" onClick={()=>removePurchase(p)}><Trash2 size={15}/>Delete</button>}{p.payable>0&&<button onClick={()=>setModal({action:'supplier_payment',title:'Pay supplier',balance:p.payable,payload:{purchase_id:p.id}})}>Pay</button>}</div></td></tr>)}</tbody></table><Pagination {...pagination}/>{!shown.length&&<div className="empty">No purchases match your search.</div>}</div>:<div className="empty">No purchases yet. Choose Add purchase to record a phone.</div>}</section>;
}
