import {Download,Printer} from 'lucide-react';
import {money} from './math.mjs';
import {purchaseHistory} from './purchaseHistory.mjs';
type Row=Record<string,any>;
type Props={data:Row;search:string;setSearch:(s:string)=>void;setModal:(v:Row)=>void;print:(purchase:Row,seller:Row|undefined)=>void;exportRows:(rows:Row[])=>void};
export default function Purchases({data,search,setSearch,setModal,print,exportRows}:Props){
 const all=data.purchases.map((p:Row)=>purchaseHistory(data,p));
 const shown=all.filter((p:Row)=>[...Object.values(p),p.seller?.full_name,p.model,p.imei].some(v=>typeof v!=='object'&&String(v??'').toLowerCase().includes(search.toLowerCase())));
 const exported=shown.map((p:Row)=>({Purchase:p.purchase_number,Seller:p.seller?.full_name||'',Date:p.purchase_date,Model:p.model,IMEI:p.imei,Total:Number(p.total_amount),Payable:p.payable,CostPending:p.costPending}));
 return <section className="panel"><div className="toolbar"><input aria-label="Search purchases" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search seller, IMEI, model or purchase…"/><div className="toolbar-actions"><button onClick={()=>exportRows(exported)}><Download size={16}/>Excel</button></div></div><div className="info">Earlier purchases without payment records show as unpaid. Reconcile these balances before relying on financial reports.</div>{all.length?<div className="table-scroll"><table><thead><tr>{['Purchase','Seller name','IMEI','Model','Date','Total','Payable','Actions'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{shown.map((p:Row)=><tr key={p.id}><td><b>#{p.purchase_number}</b></td><td>{p.seller?.full_name||'—'}</td><td>{p.phones.length?p.phones.map((i:Row)=><div key={i.id}>{i.imei_1||i.serial_number||'—'}{i.imei_2&&<small>IMEI 2: {i.imei_2}</small>}</div>):'—'}</td><td>{p.phones.map((i:Row)=><div key={i.id}>{i.model}<small>{i.storage||''}</small></div>)}{p.accessories.map((i:Row)=><div key={i.id}>{i.name}<small>Accessory</small></div>)}{!p.model&&'—'}</td><td>{new Date(p.purchase_date).toLocaleDateString('en-PK',{timeZone:'Asia/Karachi'})}</td><td>{p.costPending?'Cost pending':money(p.total_amount)}</td><td>{p.costPending?'—':p.payable>0?<b>{money(p.payable)}</b>:<span className="tag paid">Paid</span>}</td><td><div className="row-actions"><button title="Print purchase slip" onClick={()=>print(p,p.seller)}><Printer size={16}/></button>{p.phones.filter((i:Row)=>i.status!=='sold').map((i:Row)=><button key={i.id} onClick={()=>setModal({action:'inventory_edit',title:'Purchase cost · '+i.model,item:i,purchaseCostOnly:true,payload:{inventory_id:i.id}})}>{i.purchase_cost_pending?'Set purchase cost':'Edit purchase cost'}</button>)}{p.payable>0&&<button onClick={()=>setModal({action:'supplier_payment',title:'Pay supplier',balance:p.payable,payload:{purchase_id:p.id}})}>Pay</button>}</div></td></tr>)}</tbody></table>{!shown.length&&<div className="empty">No purchases match your search.</div>}</div>:<div className="empty">No purchases yet. Choose Add purchase to record a phone.</div>}</section>;
}
