import {useEffect,useRef,useState} from 'react';
import {AlertCircle,ShieldCheck,Trash2,Download} from 'lucide-react';
import {cleanupLimit,cleanupRangeError,cleanupLabels} from './cleanup.mjs';
type Preview={from:string;to:string;maximum:string;token:string;counts:Record<string,number>;protected:Record<string,number>;total:number};
type Result={backup_id:string;counts:Record<string,number>;total:number};
type Props={owner:boolean;preview:(from:string,to:string)=>Promise<Preview>;remove:(p:Preview,confirmation:string,requestId:string)=>Promise<Result>;exportBackup:(id:string)=>Promise<void>;refresh:()=>Promise<void>};
export default function RecordCleanup({owner,preview,remove,exportBackup,refresh}:Props){
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[maximum,setMaximum]=useState(cleanupLimit()),[plan,setPlan]=useState<Preview|null>(null),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Result|null>(null);
 const request=useRef(''),working=useRef(false),revision=useRef(0);
 useEffect(()=>{return()=>{revision.current++}},[]);
 if(!owner)return <div className="info">Record cleanup requires an active owner account.</div>;
 const change=(field:'from'|'to',value:string)=>{revision.current++;(field==='from'?setFrom:setTo)(value);setPlan(null);setConfirmation('');setError('');setResult(null);request.current='';};
 async function inspect(){if(working.current)return;const invalid=cleanupRangeError(from,to,maximum);if(invalid){setError(invalid);return}working.current=true;setBusy(true);setError('');setPlan(null);setResult(null);const version=revision.current;try{const next=await preview(from,to);if(version!==revision.current)return;setMaximum(next.maximum);setPlan(next);setConfirmation('');request.current=crypto.randomUUID()}catch(e:any){if(version===revision.current)setError(e.message||'Preview failed.')}finally{working.current=false;setBusy(false)}}
 const phrase=plan?`DELETE ${plan.from} TO ${plan.to}`:'';
 async function execute(){if(working.current||!plan||confirmation!==phrase)return;const invalid=cleanupRangeError(plan.from,plan.to,cleanupLimit());if(invalid){setError(invalid);setPlan(null);return}working.current=true;setBusy(true);setError('');try{const deleted=await remove(plan,confirmation,request.current);setResult(deleted);setPlan(null);setConfirmation('');try{await refresh()}catch{setError('Records were deleted. Refresh the store to load the latest data.')}}catch(e:any){setError(e.message||'Cleanup failed. If the connection was interrupted, retry with the same preview.')}finally{working.current=false;setBusy(false)}}
 return <div className="cleanup-page"><section className="panel cleanup-card"><div className="panel-head"><h3><ShieldCheck size={19}/> Current year protected</h3><span className="tag">Owner only</span></div><p>Choose an inclusive date range ending on or before <b>{maximum}</b>. The protected year changes automatically using Pakistan time. The database checks this rule again when deleting.</p><p>Active stock, unpaid balances, customer and supplier contacts, staff, accounting entries and audit history are retained. Records linked to transactions outside your range or created in the current year are skipped.</p><p>Deleted invoices, purchase details and expenses disappear from history-based reports. Accounting balances remain available. A database snapshot is created before deletion; photo files and login credentials are not included. Restoring deleted records requires a reviewed database import.</p><div className="form-grid"><label className="field"><span>From date (inclusive)</span><input type="date" value={from} max={maximum} disabled={busy} onChange={e=>change('from',e.target.value)}/></label><label className="field"><span>To date (inclusive)</span><input type="date" value={to} min={from||undefined} max={maximum} disabled={busy} onChange={e=>change('to',e.target.value)}/></label></div><button className="primary" disabled={busy||!from||!to} onClick={inspect}>{busy?'Working…':'Preview records'}</button>{error&&<div className="error" role="alert"><AlertCircle size={17}/>{error}</div>}</section>
 {plan&&<section className="panel cleanup-card"><h3>Deletion preview</h3><p>{plan.from} through {plan.to} · {plan.total} records eligible for deletion, including related line items.</p><div className="table-scroll"><table><thead><tr><th>Record type</th><th>To delete</th><th>Protected / retained in range</th></tr></thead><tbody>{Object.entries(cleanupLabels).map(([key,label])=><tr key={key}><td>{label}</td><td>{plan.counts[key]||0}</td><td>{key in plan.protected?plan.protected[key]:'—'}</td></tr>)}</tbody></table></div>{plan.total>0?<><p>Review the counts. To confirm deletion, type <b>{phrase}</b>. Export the resulting backup for a copy you can keep.</p><label className="field"><span>Deletion confirmation</span><input value={confirmation} disabled={busy} autoComplete="off" spellCheck={false} onChange={e=>setConfirmation(e.target.value)} placeholder={phrase}/></label><button className="danger" disabled={busy||confirmation!==phrase} onClick={execute}><Trash2 size={16}/>{busy?'Deleting…':'Delete eligible old records'}</button></>:<p>No eligible records. Protected records will remain saved.</p>}</section>}
 {result&&<section className="panel cleanup-card" role="status"><h3>Cleanup complete</h3><p>{result.total} old records deleted. Your protected records and accounting entries were retained.</p><button disabled={busy} onClick={async()=>{if(working.current)return;working.current=true;setBusy(true);setError('');try{await exportBackup(result.backup_id)}catch(e:any){setError(e.message||'Backup export failed.')}finally{working.current=false;setBusy(false)}}}><Download size={16}/>Export backup before deletion</button><p>Snapshots are retained for 30 days. Export this copy now if you need longer retention. It is also available in Settings → Recent snapshots.</p></section>}
 </div>;
}
