import {useState} from 'react';
import CameraScanner from './CameraScanner';
import {Camera,ScanLine} from 'lucide-react';
import {money} from './math.mjs';
import {phoneDetailLines} from './invoiceDetails';
type Row=Record<string,any>;

export default function SaleForm({data,initial}:{data:Row;initial?:string}){
 const [phone,setPhone]=useState(initial||''),[scan,setScan]=useState(''),[message,setMessage]=useState(''),[customer,setCustomer]=useState(''),[saleKind,setSaleKind]=useState('customer'),[extras,setExtras]=useState<Row[]>([]),[price,setPrice]=useState(String(data.inventory.find((p:Row)=>p.id===initial)?.default_sale_price||'')),[discount,setDiscount]=useState('0'),[camera,setCamera]=useState(false);
 const selectPhone=(id:string)=>{setPhone(id);setPrice(String(data.inventory.find((p:Row)=>p.id===id)?.default_sale_price||''))};
 const scanCode=(raw?:string)=>{const code=(raw??scan).trim();if(!code)return;const p=data.inventory.find((p:Row)=>p.status==='in_stock'&&[p.barcode_value,p.stock_code,p.imei_1,p.imei_2].includes(code));const a=data.accessories.find((a:Row)=>a.sku===code);if(p&&p.status==='in_stock'){selectPhone(p.id);setMessage('Phone added from scan.')}else if(a&&a.quantity>0){setExtras(x=>[...x,{accessory_id:a.id,name:a.name,quantity:1,price:String(a.sale_price||'')}]);setMessage('Accessory added from scan.')}else setMessage('No available item matches this barcode / IMEI.');setScan('')};
 const field=(label:string,name:string,props:Row={})=><label className="field"><span>{label}{props.required?' *':''}</span><input name={name} {...props}/></label>;
 const total=(phone?Number(price)-Number(discount):0)+extras.reduce((n,x)=>n+Number(x.price||0)*Number(x.quantity),0);
 const contacts=(data.customers||[]).filter((c:Row)=>(c.customer_kind||'customer')===saleKind);
 return <><input type="hidden" name="sale_kind" value={saleKind}/><div className="form-section">Sale type & billing</div><label className="field"><span>Sale type *</span><select value={saleKind} onChange={e=>{setSaleKind(e.target.value);setCustomer('')}}><option value="customer">Customer sale</option><option value="shopkeeper">Shopkeeper sale</option></select></label>{field('Bill made by','billed_by_name',{required:true,maxLength:120,defaultValue:data.profile?.full_name||'',placeholder:'Enter the name of the person who made this bill'})}
 <div className="form-section">Barcode / scanner</div><label className="field"><span>Scan barcode, SKU or IMEI</span><input value={scan} onChange={e=>setScan(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();scanCode()}}}/></label><div className="scanner-buttons"><button type="button" onClick={()=>scanCode()}><ScanLine size={16}/>Add scanned item</button><button type="button" onClick={()=>setCamera(true)}><Camera size={16}/>Use phone camera</button></div><p role="status" className="form-hint">{message||'USB/Bluetooth scanners work in keyboard mode. Camera scan is useful for testing on a phone.'}</p>{camera&&<CameraScanner onCode={scanCode} onClose={()=>setCamera(false)}/>}<div className="form-section">Phone (optional for accessory-only sale)</div><label className="field"><span>In-stock phone</span><select name="inventory_id" value={phone} onChange={e=>selectPhone(e.target.value)}><option value="">Accessories only</option>{data.inventory.filter((p:Row)=>p.status==='in_stock').map((p:Row)=><option key={p.id} value={p.id}>{p.model} · {p.storage} · {p.stock_code}</option>)}</select></label>{field('Phone price','price',{type:'number',min:0,step:'.01',value:phone?price:'0',onChange:(e:any)=>setPrice(e.target.value),readOnly:!phone})}{field('Discount','discount',{type:'number',min:0,step:'.01',value:phone?discount:'0',onChange:(e:any)=>setDiscount(e.target.value),readOnly:!phone})}
 <div className="form-section">Accessories / complimentary items</div><input type="hidden" name="extras_json" value={JSON.stringify(extras)}/>{extras.map((x,i)=><div className="extra-line" key={i}><input aria-label={`Item ${i+1} name`} value={x.name} required onChange={e=>setExtras(extras.map((r,j)=>j===i?{...r,name:e.target.value}:r))}/><input aria-label={`Item ${i+1} quantity`} type="number" min="1" step="1" value={x.quantity} required onChange={e=>setExtras(extras.map((r,j)=>j===i?{...r,quantity:e.target.value}:r))}/><input aria-label={`Item ${i+1} price`} placeholder="Included / no price" type="number" min="0" step=".01" value={x.price} onChange={e=>setExtras(extras.map((r,j)=>j===i?{...r,price:e.target.value}:r))}/><button type="button" onClick={()=>setExtras(extras.filter((_,j)=>j!==i))}>Remove</button></div>)}<label className="field"><span>Add stocked accessory</span><select value="" onChange={e=>{const a=data.accessories.find((a:Row)=>a.id===e.target.value);if(a)setExtras([...extras,{accessory_id:a.id,name:a.name,quantity:1,price:String(a.sale_price??'')}])}}><option value="">Choose accessory</option>{data.accessories.filter((a:Row)=>a.quantity>0).map((a:Row)=><option value={a.id} key={a.id}>{a.name} ({a.quantity})</option>)}</select></label><p className="form-hint">For a free stocked accessory, leave its selling price blank or enter 0. Its purchase cost still reduces invoice profit.</p><button type="button" onClick={()=>setExtras([...extras,{name:'',quantity:1,price:''}])}>Add other / complimentary item</button>
 <div className="form-section">Customer details</div><label className="field"><span>{saleKind==='shopkeeper'?'Shopkeeper':'Customer'} *</span><select name="customer_id" value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Add new {saleKind}</option>{contacts.map((c:Row)=><option key={c.id} value={c.id}>{c.full_name} · {c.mobile}</option>)}</select></label>{!customer&&<>{field(`${saleKind==='shopkeeper'?'Shopkeeper':'Customer'} name`,'customer_name',{required:true})}{field('Phone number (11 digits)','customer_mobile',{required:true,type:'tel',inputMode:'numeric',pattern:'[0-9]{11}',maxLength:11})}</>}
 <section className="bill-summary"><h3>Bill summary</h3><div className="table-scroll"><table><thead><tr><th>Item</th><th>Quantity</th><th>Amount</th></tr></thead><tbody>{phone&&<tr><td><b>{data.inventory.find((p:Row)=>p.id===phone)?.model}</b>{phoneDetailLines(data.inventory.find((p:Row)=>p.id===phone)).map(line=><small key={line}>{line}</small>)}</td><td>1</td><td>{money(price)}</td></tr>}{extras.map((x,i)=><tr key={i}><td>{x.name||'Item'}</td><td>{x.quantity}</td><td>{x.price===''?'Included':money(Number(x.price)*Number(x.quantity))}</td></tr>)}{phone&&Number(discount)>0&&<tr><td colSpan={2}>Discount</td><td>−{money(discount)}</td></tr>}</tbody></table></div></section><div className="bill-total-card"><span>TOTAL BILL</span><strong>{money(total)}</strong><small>Confirm the total before entering payment details.</small></div><div className="form-section">Payment details</div>{field('Received now','paid',{type:'number',required:true,min:0,max:Math.max(total,0),step:'.01',defaultValue:0})}<label className="field"><span>Payment method</span><select name="method"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="jazzcash">JazzCash</option><option value="easypaisa">EasyPaisa</option></select></label><p className="form-hint">Any unpaid balance is recorded against this {saleKind}'s ledger.</p></>;
}
